### ISSUE TITLE
mdm table using wrong source for profiles timeout calculation? 

### ISSUE THREAD

**Issue by discentem** [macadmins/osquery-extension#16]
I think it should be `/private/var/db/ConfigurationProfiles/Settings/.profilesFetchTimerCheck` per https://macadmins.slack.com/archives/C4ENKD38A/p1647982679639689?thread_ts=1647982148.698809&cid=C4ENKD38A

**Comment by grahamgilbert** [comment]
That file is not present on a machine that is not enrolled in MDM. This table needs to work on devices that are both enrolled in MDM and that that are not.

**Comment by joncrain** [comment]
I ran through these scenarios again. If a machine is not in DEP at all, neither of these files exist. 
However, when running the profiles command it appears that the following:

`profiles show` does create the timer for this specific command in  `/private/var/db/ConfigurationProfiles/Settings/.profilesFetchTimerCheck` under the `lastProfilesShowFetchTime` key.

The `. cloudConfigTimerCheck` is updated when any of the following `show`, `validate`, or `renew` is run.

**Comment by grahamgilbert** [comment]
I thought the rate limit was a global one across those three commands. If that’s the case, we are looking at the right file still. If not, then we need to change. How to validate this?

**Comment by erikng** [comment]
I believe the other commands use the cache which is why they are not "rate limited"

**Comment by grahamgilbert** [comment]
Until we can prove this one way or the other I think I’m going to leave this as it is. It works fine in my testing, so until we have more evidence (or even GASP, documentation from apple), this can stay as it is.

**Comment by erikng** [comment]
Easy test would be to yank network from a machine and run the commands.

**Comment by grahamgilbert** [comment]
Closing this until an interested party disproves the method I chose.
