### ISSUE TITLE
Error generating unified log

### ISSUE THREAD

**Issue by zwass** [macadmins/osquery-extension#20]
```
osquery> select * from unified_log where last = '10h' AND subsystem = 'com.apple.ManagedClient.cloudconfigurationd' limit 10;
Error: error generating table: json: cannot unmarshal number 9223372620970852356 into Go struct field UnifiedLog.traceID of type int64
```

**Comment by zwass** [comment]
Sample of log that generated this:

```
  "traceID" : 9223372620970852356,
  "eventMessage" : "[IOUserUSBHostHIDDevice.cpp:936][0x10000dca5] CompleteInReport:0xe00002eb",
  "eventType" : "logEvent",
  "source" : null,
  "formatString" : "%s",
  "activityIdentifier" : 0,
  "subsystem" : "",
  "category" : "",
  "threadID" : 3254651,
  ```
I think we can fix it by changing `TraceID` to `uint64`. I wonder if anything else should be made `uint64`?

**Comment by discentem** [comment]
`uint64` makes sense to me. I assume `traceID` would never be negative in practice 😅 ?  I'm not as sure about the other `int` fields always being positive but if you are confident about those fields or have seen other error cases, definitely can change them too.

**Comment by zwass** [comment]
I'm not confident, nor have I seen any examples of failures for other fields. Maybe we should go with `big.Int` for `TraceID` if we think there's a chance it could go negative? 😰

**Comment by discentem** [comment]
With regards to `traceID`, I think it makes sense to change to uint64. 

If you don't have a pressing need to change other fields maybe we leave those for now?
