### ISSUE TITLE
Error on install osquery-extension.  I am using Linux

### ISSUE THREAD

**Issue by sreenik250** [macadmins/osquery-extension#33]
❯ make
mkdir -p build/Darwin
mkdir -p build/windows
mkdir -p build/linux
GOOS=darwin GOARCH=amd64 go build -o build/darwin/macadmins_extension.amd64.ext
go: downloading github.com/osquery/osquery-go v0.0.0-20220317165851-954ac78f381f
go: downloading github.com/groob/plist v0.0.0-20220217120414-63fa881b19a5
go: downloading github.com/pkg/errors v0.9.1
go: downloading gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
go: downloading github.com/apache/thrift v0.16.0
GOOS=darwin GOARCH=arm64 go build -o build/darwin/macadmins_extension.arm64.ext
/usr/bin/lipo -create -output build/darwin/macadmins_extension.ext build/darwin/macadmins_extension.amd64.ext build/darwin/macadmins_extension.arm64.ext
make: /usr/bin/lipo: No such file or directory
make: *** [Makefile:36: build] Error 127

**Comment by grahamgilbert** [comment]
This isn’t how you install this tool. Download the zip from [the releases page](https://github.com/macadmins/osquery-extension/releases) and use the built binary for your chosen platform and architecture.
