### ISSUE TITLE
The executable does not have the hardened runtime enabled

### ISSUE THREAD

**Issue by tomasz-hofy** [macadmins/osquery-extension#44]
Hi,
I am trying to bundle osquery-extension and osquery, and in the notarization process I am getting the following error  from Apple.
Error is related to extension extracted from Release binary.
```
The executable does not have the hardened runtime enabled
```
Could you advice how to fix this problem ?

**Comment by grahamgilbert** [comment]
Notarization is not required for enterprise deployment methods (such as munki).
